/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'LogGreeting': EventHandler<{ requestId: string; greeting: string; processedBy: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'UploadDocument': ApiRouteHandler<Record<string, unknown>, ApiResponse<201, { document_id: string; filename: string; status: string; message: string }> | ApiResponse<400, { error: string }> | ApiResponse<500, { error: string }>, { topic: 'document.uploaded'; data: never }>
    'SaveDocument': EventHandler<never, never>
    'ListDocuments': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetDocument': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { document_id: string; filename: string; document_type: string; status: string; extracted_text: string | unknown; ai_summary: string | unknown; risk_score: number | unknown; uploaded_at: string; processed_at: string | unknown; reviewer_comments: string | unknown }> | ApiResponse<404, { error: string }>, never>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, { topic: 'greeting-processed'; data: { requestId: string; greeting: string; processedBy: string } }>
  }
    
}